Add async capabilities to protocols
bluesky/bluesky pull request #1522
Opened 2022-05-26 14:42 UTC by coretl

To better document how Bluesky interfaces with hardware and make the asyncio compatible.
Supersedes #1502 

## Description
- 

## Motivation and Context
So I can write Ophyd.v2

## How Has This Been Tested?
Unit tests pass

2022-05-26 15:55 UTC, coretl commented on bluesky/run_engine.py
> +                fut = asyncio.run_coroutine_threadsafe(maybe_await(obj.resume()), self._loop)
I think this is safe, but it is messy. Maybe #1521 will solve it?

2022-05-26 15:56 UTC, coretl commented on bluesky/run_engine.py
> +        await self._stop_movable_objects(success=True)
These awaits are in a plan, so I think they are safe

2022-05-26 15:57 UTC, coretl commented on bluesky/run_engine.py
> +                fut = asyncio.run_coroutine_threadsafe(maybe_await(obj.resume()), self._loop)
@tacaswell this is the area of code that most needs reviewing

2022-05-26 20:48 UTC, untzag requested changes
The signature for `Movable` breaks ophyd and yaqc-bluesky. The following class should pass mypy:

```python
from ophyd.status import Status
class Device:
    def set(self, value: float) -> Status:
         ...
```

If you just go back to the old signature it should work for anything you could imagine...

Note that I'm talking about static type checking, not runtime checking! We have some tests for this:

- https://github.com/bluesky/yaqc-bluesky/blob/master/bluesky_protocols.py
- https://github.com/bluesky/ophyd/blob/master/ophyd/tests/test_bluesky_protocols.py

In my opinion these tests should pass before merge.

2022-05-31 15:46 UTC, ksunden commented
I tend to agree with @untzag, though the `float` annotation does not capture the fullness of what can be passed there... the point is that to my understanding, timeout is not a required kwarg, it is an implementation detail and to type check actual implementations, all that is required is a single positional argument. 

(I personally tend towards devices where that _is_ a float, but various devices use either arrays, str, or dict for various reasons, and not sure we can narrow that type)

I will note that something specified as a single positional argument does type check against an implementation which allows variadic args and kwargs just fine, but that is an implementation detail of the particular library.

2022-06-06 10:48 UTC, coretl commented
I didn't know there were those tests, I've put the original definition back as adding anything to the type signature would require all implementers to add it to the implementation

2022-06-06 16:10 UTC, coretl commented
BTW the docs build error should go away once #1524 is merged

2022-06-08 15:18 UTC, merged